services:
  - type: web
    name: codestart-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGO_URI
        fromDatabase:
          name: codestart-mongodb
          key: connectionString
      - key: JWT_SECRET
        value: your_jwt_secret_here
      - key: JWT_EXPIRE
        value: "30d"
      - key: JWT_COOKIE_EXPIRE
        value: "30"
    autoDeploy: true
    healthCheckPath: /api/modules
